version: '3.9'

services:
  fengshui-api:
    depends_on:
      - postgres-db
    build: ./
    env_file: ./.env
    ports:
      - "8081:8080"
    environment:
      JPDA_ADDRESS: 5005
      JPDA_TRANSPORT: dt_socket
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres-db:5432/FengshuiApp",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "12345",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
   
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: FengshuiApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
